### ISSUE TITLE
Update website to point to v5.3.1

### ISSUE THREAD

**Issue by marcjansen** [openlayers/openlayers.github.io#100]
The website currently shows 5.3.0 as latest release, while [we released 5.3.1](https://github.com/openlayers/openlayers/pull/9255) some days ago.

Would updating simply mean the following?

```
# in a clone of this repo
# on the deploy branch
$  treeish=v5.3.1 npm run deploy
```

**Comment by ahocevar** [comment]
The `build` branch is the one to use. Other than that, this is correct.

**Comment by ahocevar** [comment]
However, we'd get incorrect Mapbox API keys and no cookie warnings, so I'd not create a new website for v5.3.1.

**Comment by marcjansen** [comment]
> However, due to changes we had to make that are not in 5.3.1, we'd get incorrect Mapbox API keys and no cookie warnings, so I'd not create a new website for v5.3.1.

OK

**Comment by marcjansen** [comment]
Would it make sense to at least link to v5.3.1 from the main page?
