### ISSUE TITLE
X-Content-Type-Options: nosniff

### ISSUE THREAD

**Issue by xycarto** [openlayers/openlayers.github.io#114]
I recently built a site using the following tags in my HTML:

```
<html lang="en" xml:lang="en" xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta charset="UTF-8" name="viewport" content="user-scalable=no, width=device-width, height=device-height, maximum-scale=1.0, minimum-scale=1.0, initial-scale=1.0">
        <title>OpenLayers example</title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/v6.5.0/css/ol.css" type="text/css">
        <link rel="stylesheet" href="style.css" />
        <script src="https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/v6.5.0/build/ol.js"></script>
        <script src="https://unpkg.com/ol-mapbox-style@6.3.2/dist/olms.js" type="text/javascript"></script>
        
    </head>
```

Everything was working fine until a few hours ago. Now I am getting:

```
The resource from “https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/v6.5.0/build/ol.js” was blocked due to MIME type (“text/plain”) mismatch (X-Content-Type-Options: nosniff).
```

Nothing has changed on my end for the last several days.

Did something change on the Openlayers side?

The issue seems to arise in Firefox, Chrome, and Chromium.  Somehow, it is fine in Safari.

**Comment by ahocevar** [comment]
I just checked the URL (https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/v6.5.0/build/ol.js), and it correctly returns `application/javascript` as MIME type. Maybe this was a temporary issue with https://cdn.jsdelivr.net.

As you can find in our documentation in many places, we discourage the use of script and css resources from CDNs in production. These may be nice for quick prototyping, but when you run an application in production, it is always a good idea to build the application together with its dependencies, using a bundler like webpack or parcel. When you have a server to host your static app files, you have everything you need to go that route. Relying on external resources you cannot control is an unnecessary point of failure.

**Comment by symbioquine** [comment]
For the jsDelivr issue see https://github.com/openlayers/openlayers.github.io/issues/113

**Comment by xycarto** [comment]
Thank you all for the response and advice.

Also thanks for all the great work on Openlayers
