### ISSUE TITLE
Codesandbox links not working for examples

### ISSUE THREAD

**Issue by jansule** [openlayers/openlayers.github.io#117]
The links to codesandbox in the examples do not work. They point to `https://codesandbox.io/api/v1/sandboxes/define` which only shows following error message:

```json
{"error":"This endpoint requires the params `files` or `parameters` in order to work. See https://codesandbox.io/docs/importing#create-wizard for more details."}
```

Steps to reproduce:

1. Open an OpenLayers Example (e.g. https://openlayers.org/en/latest/examples/vector-layer.html)
2. Click on the `Edit` button in the upper right corner

**Comment by ahocevar** [comment]
Maybe this was a temporary issue with codesandbox.io? I cannot reproduce it right now.
