### ISSUE TITLE
Version 6.8.1 disappeared

### ISSUE THREAD

**Issue by lukin0z** [openlayers/openlayers.github.io#128]
Hi everyone,
thanks a lot for your great project.
We noticed that this path: https://github.com/openlayers/openlayers.github.io/tree/master/en/v6.8.1/ is disappeared from the Github project.
We have some projects that link this path.
Do we have to move our project to the 6.9 version, or did you plan to restore the 6.8 version path?

Thanks a lot.

Best regards,
Luca.

**Comment by ahocevar** [comment]
Please use a local copy of OpenLayers, ur change the link to 6.15.1. The former is the preferred option.

**Comment by lukin0z** [comment]
Thanks a lot for your reply
