### ISSUE TITLE
Missing build v6.4.3 from CDN

### ISSUE THREAD

**Issue by Gedridze** [openlayers/openlayers.github.io#129]
The CDN links: https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/v6.4.3/build/ol.js and https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/v6.4.3/css/ol.css are no longer working. Our web is deployed on many devices so it is impossible to manually update the links, could it be possible to return this version back to the cdn?

**Comment by UrielMendoza** [comment]
I have the same problem with v6.2.1, i know it's a bad practice, but all the code was building with this version and i don't have too much time to change to npm

**Comment by UrielMendoza** [comment]
> The CDN links: https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/v6.4.3/build/ol.js and https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/v6.4.3/css/ol.css are no longer working. Our web is deployed on many devices so it is impossible to manually update the links, could it be possible to return this version back to the cdn?

i solved the problem with this link:

https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/v6.15.1/build/ol.js
 
You can try.

**Comment by Gedridze** [comment]
> i solved the problem with this link:
> 
> https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/v6.15.1/build/ol.js
> 
> You can try.

Our software runs on multiple devices and such change would require all clients to update their software version for maps to work again and it would not be optimal. I see that there are already a handful of versions in this folder: https://github.com/openlayers/openlayers.github.io/tree/master/en so I think it would be possible to add another one. Such a solution would fix the problem on our side without the need of software updates from clients.

**Comment by ahocevar** [comment]
@Gerizde @UrielMendoza You really should not be publishing software on devices with dependencies to external resources that point to the head of a branch of a repository. But since it looks like you're in trouble because of this, I just put versions 6.2.1 and 6.4.3 back there.

Oh, and in case you're interested, there is https://github.com/sponsors/ahocevar
