### ISSUE TITLE
CSS style mistake

### ISSUE THREAD

**Issue by barnoma-soz** [openlayers/openlayers.github.io#131]
Hi.
You have css style mistake on page concepts.html

`<div id="map" style="width: 100%, height: 400px"></div>`

should be

`<div id="map" style="width: 100%; height: 400px"></div>`

**Comment by jahow** [comment]
Good catch, thanks! Note that the source code for the website is here:
https://github.com/openlayers/openlayers/blob/main/site/src

And the specific file that you mention is here:
https://github.com/openlayers/openlayers/blob/main/site/src/doc/tutorials/concepts.md

Would you be able to provide a Pull Request for fixing this file? That would be greatly appreciated, thanks in advance!
