### ISSUE TITLE
Navigation hidden

### ISSUE THREAD

**Issue by tschaub** [openlayers/openlayers.github.io#23]
When viewing [the site](http://ol3js.org/) in Chrome 34, I don't see the navigation links (docs, examples, code).  Making the page narrow, clicking on the menu button, and then making the page wide again causes the navigation to reappear.

**Comment by fredj** [comment]
It's happening again on http://openlayers.org/

**Comment by ahocevar** [comment]
Looks like someone who hasn't updated their openlayers.github.io dependencies has rebuilt the website. I've seen this once or twice already, and after I rebuilt the website, everything was fine again. Who was the last person who rebuilt the website?

**Comment by elemoine** [comment]
I did. I'll rebuild tomorrow.

**Comment by elemoine** [comment]
It should be fixed. I had to delete the content of `bower_components` because I had a version of jQuery (2.0.3) which did not have the "dist" directory in `bower_components/jquery`.
