### ISSUE TITLE
Home page should mention cdnjs.com files

### ISSUE THREAD

**Issue by probins** [openlayers/openlayers.github.io#48]
shouldn't it?

**Comment by bartvde** [comment]
IIRC the upcoming download page that @klokantech is working on will have this info

**Comment by blueyed** [comment]
As of now it does not mention it: http://openlayers.org/download/

Also relevant: accessing the JS through https: https://github.com/openlayers/openlayers.github.io/issues/53.

**Comment by fredj** [comment]
pull request accepted !

**Comment by blueyed** [comment]
@fredj 
Where are the docs hostest?

/cc @klokan

**Comment by fredj** [comment]
You need to update https://github.com/openlayers/openlayers.github.io/blob/build/src/pages/download/index.hbs
