### ISSUE TITLE
Access to API JS through https

### ISSUE THREAD

**Issue by blueyed** [openlayers/openlayers.github.io#53]
I've tried to use a protocol-relative URL to OpenLayers.js in Django (https://code.djangoproject.com/ticket/25436), but it fails, because https://openlayers.org/api/2.13.1/OpenLayers.js cannot be accessed (times out).

When trying to use the github.io subdomain, it  redirects:

    % curl -I http://openlayers.github.io/api/2.13.1/OpenLayers.js
    HTTP/1.1 301 Moved Permanently
    [...]
    Location: http://openlayers.org/api/2.13.1/OpenLayers.js

Can this be supported?
Should Django use cdnjs, or another similar service instead?

**Comment by jimaek** [comment]
How about http://www.jsdelivr.com/projects/openlayers ?

**Comment by blueyed** [comment]
@jimaek 
Yeah, it seems to be similar to https://cdnjs.com/libraries/openlayers.

For the fix in Django I'd like to use the recommended version/CDN.
And this should then be mentioned on the homepage / download page, too (https://github.com/openlayers/openlayers.github.io/issues/48).

Apart from that, it would be nice to fix access through https to the version on github.io anyway (this issue), if that is possible.

**Comment by probins** [comment]
I would say you should use https://cdnjs.cloudflare.com/ajax/libs/openlayers/2.13.1/OpenLayers.js

**Comment by probins** [comment]
this should be fixed now

**Comment by blueyed** [comment]
@probins 
Thanks!
Closing this issue here then.
As for Django: it uses cdnjs (IIRC), which makes sense in general.
