### ISSUE TITLE
http://openlayers.org/ IE9 issue

### ISSUE THREAD

**Issue by fredj** [openlayers/openlayers.github.io#63]
The map is not displayed because the requestAnimationFrame polyfill is not loaded

**Comment by ahocevar** [comment]
Interesting. I wonder why that is, because the test template includes the polyfill. Url from http://openlayers.org/en/v3.14.1/examples/simple.html: `https://cdn.polyfill.io/v2/polyfill.min.js?features=fetch,requestAnimationFrame`.

**Comment by ahocevar** [comment]
Ah, I see what you mean. The main page http://openlayers.org/. Thanks for spotting this.
