### ISSUE TITLE
Change to using Cloudflare as front-end?

### ISSUE THREAD

**Issue by probins** [openlayers/openlayers.github.io#68]
I'm doing this with my own Github Pages site now, and it has several advantages. The main one is that they provide a basic form of SSL, so pages stored on Github pages can be served with https (Github itself only partly supports this). This is though not properly secure, and shouldn't be used for sensitive data, but I don't think this applies to what openlayers.org is serving anyway. They recently introduced a force https option, so all http requests are automatically served as https. This should fix #53, and also https://github.com/openlayers/ol3/issues/5276. There's also an option to use http/2 (I believe this is now the default), and this should speed up for example the loading of the 'raw' examples. There are various other useful options, such as caching, all available with the free plan.

**Comment by fredj** [comment]
+1 !

**Comment by fredj** [comment]
only he dns servers needs to changed?

**Comment by probins** [comment]
yes. I'd suggest setting up an account on Cloudflare first and configuring it. Then change the domain name to point to Cloudflare's name servers once that's all done.

**Comment by probins** [comment]
looks like this has now been done https://github.com/openlayers/ol3/pull/5966#issuecomment-254003079
