### ISSUE TITLE
Website build process broken

### ISSUE THREAD

**Issue by ahocevar** [openlayers/openlayers.github.io#69]
Since the latest updates, the versioned website directories are not created properly any more. See https://groups.google.com/d/msgid/ol3-dev/CACPZzQ1sWtB7%3DmXB2HvPVa01RMAWfZDoJVQBQxYaUS-xjtM4cg%40mail.gmail.com?utm_medium=email&utm_source=footer.

I am currently building the website with a previous version of the build branch, and will then be working on a fix.

**Comment by ahocevar** [comment]
Fixed with f4d59528159d0010774feed19e24f5aee65e7dc4.

**Comment by marcjansen** [comment]
Thanks a lot, Andreas!
