### ISSUE TITLE
Plugins

### ISSUE THREAD

**Issue by jonataswalker** [openlayers/openlayers.github.io#74]
Moving an extract of [this conversation](https://groups.google.com/forum/#!topic/ol3-dev/QAkWLgmg74M) to get help in next steps.

> Well, actually, I'm a bit lost where to put things.
> 
> What I have in mind is:
> - create an entry (Plugins) at main menu.
>   - it seems to me this is https://github.com/openlayers/openlayers.github.io/blob/build/src/layouts/main.hbs
> - the created entry would link to http://openlayers.org/en/latest/doc/plugins.html
>   - this would be plugins.md inside https://github.com/openlayers/ol3/blob/master/doc/
> 
> But what about:
>   git add some-path/to/plugins.md
>   git commit ...
>   git push ...
> 
> Is this done with npm run deploy?

**Comment by jonataswalker** [comment]
I need some help to proceed.

ping @ahocevar

**Comment by tschaub** [comment]
@jonataswalker you can create a new plugins page in the https://github.com/openlayers/openlayers.github.io/tree/build/src/pages directory.  The `build` branch is the default branch (don't commit directly to `master`), and you'll find the source for the [index page](https://github.com/openlayers/openlayers.github.io/blob/build/src/pages/index.hbs), the [sponsors page](https://github.com/openlayers/openlayers.github.io/blob/build/src/pages/sponsors.hbs), and the [download page](https://github.com/openlayers/openlayers.github.io/blob/build/src/pages/download/index.hbs) there.

So, create a new branch based off of the `build` branch, and then add a `src/pages/plugins/index.hbs` page.

To preview the page, you can `npm install && npm start`.  This takes a crazy long time for the first build currently, would be great to rework how the website is built.  This will pull in and build additional content from the [main repo](https://github.com/openlayers/ol3).

To get your page deployed, please create a pull request (against the `build` branch) and have it reviewed.  Thanks!

**Comment by jonataswalker** [comment]
Great @tschaub. PR #76 created.
