### ISSUE TITLE
Links to source code exact lines are broken from lowercase L

### ISSUE THREAD

**Issue by matthiasdailey-ccri** [openlayers/openlayers.github.io#77]
The links to the GitHub source code (exact lines) are broken. They have an anchor to the exact line, like "#l234", but this should be a capital L, like "L234".

To reproduce:
Go to http://openlayers.org/en/latest/apidoc/ol.source.Vector.html#clear
At the top right, click the link "line 382".
It goes to the right source code page, but it doesn't go to the anchor for the line number.
It goes to https://github.com/openlayers/ol3/blob/v3.17.1/src/ol/source/vectorsource.js#l382
If you change the URL to use a capital L, then it works:
https://github.com/openlayers/ol3/blob/v3.17.1/src/ol/source/vectorsource.js#L382

I don't know if the lowercase is a recent change, or if you have always had it lowercase and GitHub only recently removed support for case-insensitivity. GitHub uses a capital L for its own links, presumably to avoid ambiguity between l, 1, and I.

**Comment by ahocevar** [comment]
Fixed with openlayers/ol3#5669. The website will be updated with the next release.

**Comment by matthiasdailey-ccri** [comment]
Although this has been fixed in the "latest" version of the docs, it is still present for previous versions.
Compare the source links on [latest](http://openlayers.org/en/latest/apidoc/ol.Attribution.html) (fixed) versus [3.14.2](http://openlayers.org/en/v3.14.2/apidoc/ol.Attribution.html) (broken)

**Comment by matthiasdailey-ccri** [comment]
Still broken for previous version docs

**Comment by matthiasdailey-ccri** [comment]
@ahocevar this is still broken for previous versions.

**Comment by ahocevar** [comment]
The website is built automatically for each release. The fix in openlayers/ol3#5669 won't fix any release that was built before the fix.
