### ISSUE TITLE
no link to v4 documentation?

### ISSUE THREAD

**Issue by larkin** [openlayers/openlayers.github.io#95]
Earlier this year I started a project on v4 and felt that the API docs were very useful and applicable to my usage.  Today I went back to tweak how some touch interactions were handled in my project, and I found that the v4 API documentation was missing and all that I am able to see is v5 documentation... there's a link to v2 documentation, but why not a link to v4 documentation?

The v5 documentation seems much harder to navigate and find concrete descriptions of the interactions compared to the v4 documentation.  Additionally, it looks like the API has changed, so it's not much use to me.

Can you continue to host the v4 API documentation the same as [many](https://jasmine.github.io/pages/docs_home.html) [other](https://user-images.githubusercontent.com/226503/43929825-6f2e1b80-9beb-11e8-823a-48852c5dfcc5.png) [projects](https://leafletjs.com/reference-versions.html) continue to host older versions of their API docs?

**Comment by fredj** [comment]
You can access the v4 API documentation at:
https://openlayers.org/en/v4.6.5/apidoc/

The examples are also available at: https://openlayers.org/en/v4.6.5/examples/

**Comment by larkin** [comment]
@fredj thank you!  I could not find this by googling or by browsing the openlayers website... Is there a place on the website to find links to older documentation versions?

**Comment by fredj** [comment]
You can find the list of all the releases here: https://github.com/openlayers/openlayers/tags
